<?php

declare( strict_types=1 );

namespace NanoPress;

/**
 * Loads build assets generated by the WordPress scripts toolchain.
 */
class Asset_Loader {

	/**
	 * Enqueues a built script.
	 *
	 * @param string                    $handle     Script handle suffix.
	 * @param string                    $file_name  Path inside the build directory without extension.
	 * @param array<string, mixed>|null $asset_data Optional asset metadata.
	 */
	public static function enqueue_script( string $handle, string $file_name, ?array $asset_data = null ): void {
		$script_path       = NANOPRESS_PLUGIN_DIR . 'build/' . $file_name . '.js';
		$script_url        = NANOPRESS_PLUGIN_URL . 'build/' . $file_name . '.js';
		$script_asset_path = substr( $script_path, 0, -3 ) . '.asset.php';

		if ( ! file_exists( $script_path ) ) {
			return;
		}

		if ( ! is_array( $asset_data ) && file_exists( $script_asset_path ) ) {
			$asset_data = require $script_asset_path; // phpcs:ignore WordPressVIPMinimum.Files.IncludingFile.UsingVariable
		}

		if ( ! is_array( $asset_data ) ) {
			$asset_data = array(
				'dependencies' => array(),
				'version'      => filemtime( $script_path ),
			);
		}

		wp_enqueue_script(
			'nanopress_' . $handle,
			$script_url,
			$asset_data['dependencies'] ?? array(),
			$asset_data['version'] ?? filemtime( $script_path ),
			array( 'strategy' => 'defer' )
		);
	}

	/**
	 * Enqueues a built stylesheet.
	 *
	 * @param string $handle    Style handle suffix.
	 * @param string $file_name Path inside the build directory without extension.
	 */
	public static function enqueue_style( string $handle, string $file_name ): void {
		$style_path = NANOPRESS_PLUGIN_DIR . 'build/' . $file_name . '.css';
		$style_url  = NANOPRESS_PLUGIN_URL . 'build/' . $file_name . '.css';

		if ( ! file_exists( $style_path ) ) {
			return;
		}

		wp_enqueue_style(
			'nanopress_' . $handle,
			$style_url,
			array(),
			(string) filemtime( $style_path )
		);
	}
}
